/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef C_CPP_H
#define C_CPP_H

#ifdef _WIN32
#define C_CPP_EXPORT_FUNC __declspec(dllexport)
#else
#define C_CPP_EXPORT_FUNC
#endif

#include <string>

namespace c_cpp {
    class Greeter {
        public:
        std::string C_CPP_EXPORT_FUNC greeting();
    };
}

#endif
